### ISSUE TITLE
cannot read property 'result' of undefined

### ISSUE THREAD

**Issue by ThaddeusKKR** [galnir/Master-Bot#107]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs.

**Describe the bug**
I get an error when trying to search lyrics -> "Something went wrong, please try again or be more specific"

**To Reproduce**
1. Search a song (I specifically used this: "Call Me Maybe - Carly Rae Jepsen (Lyrics) 🎵")
2. Do the lyrics command

**Expected behavior**
Lyrics should come out fine

**Screenshots**
I used this song:
![image](https://user-images.githubusercontent.com/49682825/86511458-0cc07780-be2c-11ea-85a5-e58ec491dca0.png)

**Desktop (please complete the following information):**
 - OS: its heroku so i dont really know
 - Node Version(Should be v12 atleast): 12.18.1
 - Are python 2.7 and Ffmpeg installed?: Yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): heroku

**Additional context**
Error in console:
```js
2020-07-04T11:22:54.754750+00:00 app[worker.1]: TypeError: Cannot read property 'result' of undefined
2020-07-04T11:22:54.754760+00:00 app[worker.1]:     at LyricsCommand.run (/app/commands/music/lyrics.js:56:48)
2020-07-04T11:22:54.754760+00:00 app[worker.1]:     at runMicrotasks (<anonymous>)
2020-07-04T11:22:54.754761+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-07-04T11:22:54.754762+00:00 app[worker.1]:     at async CommandoMessage.run (/app/node_modules/discord.js-commando/src/extensions/message.js:235:20)
2020-07-04T11:22:54.754762+00:00 app[worker.1]:     at async CommandDispatcher.handleMessage (/app/node_modules/discord.js-commando/src/dispatcher.js:143:19)
```

**Comment by galnir** [comment]
Pull the changes I just pushed(2a599a6) that will get rid of the error message. The problem is that the Genius API is not consistent and may work and may not work for the same input. I'm looking into alternatives because that API basically sucks

**Comment by ThaddeusKKR** [comment]
I've done it, but although the console error has been removed, the `Something went wrong, please try again or be more specific` error remains.

**Comment by galnir** [comment]
@ThaddeusKKR  I'm going to commit a fix that may solve that in a few mins

**Comment by galnir** [comment]
6a92d6d should solve it. As I said sometimes you might search for lyrics and it'll return that message, then you can search again and it'll find them. I'm looking into alternatives to that api

**Comment by ThaddeusKKR** [comment]
Yep, it worked, thanks!
