### ISSUE TITLE
Cannot read property 'leave' of undefined

### ISSUE THREAD

**Issue by iNPGT** [galnir/Master-Bot#11]
TypeError: connection.play is not a function
    at queue.(anonymous function).voiceChannel.join.then.connection 

(C:\Users\Roman\Desktop\INPGT-BOT\commands\music\play.js:241:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13548) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'leave' of undefined
    at queue.(anonymous function).voiceChannel.join.then.catch.e 

(C:\Users\Roman\Desktop\INPGT-BOT\commands\music\play.js:273:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)

(node:13548) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:13548) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by iNPGT** [comment]
welp

**Comment by galnir** [comment]
What did you try to do that fired this error?

**Comment by nmbarker** [comment]
I also got this issue when running play followed by a youtube link. When I try the "leave" command, I get this error from the bot:
`TypeError: Cannot set property 'length' of undefined`

Been looking around, nothing seems to work.

**Comment by galnir** [comment]
@nmbarker I'll debug this today, thanks for letting me know

**Comment by galnir** [comment]
@nmbarker @iNPGT I pushed a new commit, can you check if that solves the problem? Works on my end

**Comment by nmbarker** [comment]
Alright the leave command is "fixed." If there is no music and I want it to leave, it won't leave. I will try to fix on my own but I still get the error:
`(node:10513) DeprecationWarning: Collection#filterArray: use Collection#filter instead
TypeError: connection.play is not a function
    at queue.(anonymous function).voiceChannel.join.then.connection (/home/projectcamel/camel/commands/music/play.js:259:10)
    at <anonymous>
(node:10513) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'leave' of undefined
    at queue.(anonymous function).voiceChannel.join.then.catch.e (/home/projectcamel/camel/commands/music/play.js:295:27)
    at <anonymous>
(node:10513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10513) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

When ever I try to play a song with the command 
`>play <insert youtube link here>`
Where ">" is my prefix.

**Comment by galnir** [comment]
How did you get the bot to be on the channel and not play music? When there are no songs left in the queue the bot automatically leaves the channel.

**Comment by nmbarker** [comment]
Alright so when I use the >play command it spits out that error into my console and plays no music so the bot stays in the channel indefinitely. Don't know why it happens, been debugging since last night and nothing seems to work. It has something to do with `connection.play` not being a function.

**Comment by galnir** [comment]
The problem with running Discord bots is they require tough set up and installation of many stuff like python 2.7, ffmpeg, and some linux packages if you're running on linux. It took me a week to get rid of errors on my Windows machine and Debian 9 machine(main bot machine). 
What OS are you using?

**Comment by nmbarker** [comment]
Running a Compute Engine on Google Cloud.
Current OS Version: Ubuntu 18.04.1 LTS (Bionic Beaver)

**Comment by galnir** [comment]
Is the link you're providing as an argument is a playlist?

**Comment by nmbarker** [comment]
No, the test video I've been using is: [https://www.youtube.com/watch?v=Cuyd2rgIBWg](url)

**Comment by galnir** [comment]
![xEBl4GwUP4](https://user-images.githubusercontent.com/36937694/64130884-cf372c00-cdcd-11e9-876e-4932b98649ab.gif)

This works on my end(no audio cuz gif), I'm trying to figure out what is the issue, I probably forgot to mention some package that you should install in the README

**Comment by nmbarker** [comment]
Alright, just let me know. I appreciate it.

**Comment by galnir** [comment]
@nmbarker Can you run `apt list ffmpeg` on your ubuntu terminal and check if it is installed and up to date?

**Comment by nmbarker** [comment]
What is the most recent version of ffmpeg? 
apt list ffmpeg spits out
`ffmpeg/bionic-updates,bionic-security,now 7:3.4.6-0ubuntu0.18.04.1 amd64 [installed]`

**Comment by galnir** [comment]
@nmbarker Mine spits out `ffmpeg/stable,stable,now 7:3.2.12-1~deb9u1 amd64 [installed]`. There might be a slight chance the installed version you have is not correct.

Before I seek other solutions, please try to follow these 2 articles:
1. [Uninstall ffmpeg](https://www.lifewire.com/uninstall-software-on-ubuntu-4125348)
2. [Install ffmpeg again](https://itsfoss.com/ffmpeg/#install)

There is a ytdl package a discord.js dev published which avoides using ffmpeg for playing most music. I tried to use it but ran into many errors since it is still new, hopefully somewhere in the future I will replace ytdl-core with it.

**Comment by nmbarker** [comment]
Still no dice, it still says that connection.play is not a function

**Comment by galnir** [comment]
It doesn't make sense, .play is a function in discord.js/master it's literally on the docs.. I'll keep looking for solutions idk why it works on my end and not on yours

**Comment by nmbarker** [comment]
Do you want to move this conversation into a discord just so I'm not blowing up your github inbox?

**Comment by galnir** [comment]
hyperzone#1185

**Comment by galnir** [comment]
@iNPGT If you didn't clone the repo, replace the versions of discord.js and discord.js commando in your **package.json** with:
`    "discord.js": "github:discordjs/discord.js#master",`
`    "discord.js-commando": "github:discordjs/Commando"`

That fixed the problem for nmbarker

**Comment by OBNinjaa** [comment]
Must be you because it works fine for me.

**Comment by galnir** [comment]
Will reopen if that won't solve it for you
