### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Jriskamm** [galnir/Master-Bot#433]
TypeError: Cannot read property 'split' of undefined

<img width="471" alt="Screenshot (9)" src="https://user-images.githubusercontent.com/69320092/106372340-aa236000-63a9-11eb-813c-05728417fa5a.png">
Happens when  /play https://youtube.com/playlist?list=PL3oW2tjiIxvSk0WKXaEiDY78KKbKghOOo

i copied the whole play.js file

**Comment by Natemo6348** [comment]
If you copied code from this repo then there's nothing we can help you with, as [bug_report.md](https://github.com/galnir/Master-Bot/tree/master/.github/ISSUE_TEMPLATE/bug_report.md) says 'Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.'

**Comment by Natemo6348** [comment]
Umm, I just got this error when running add-to-playlist command. The URL I used is https://youtube.com/playlist?list=PLQ7dL0qYMW8h2-F4p1ULlRw3kY5pLMAm_

**Comment by Natemo6348** [comment]
Also I'd like to say that I didn't just copy code, this is an almost fresh clone. The changes I made don't interfere with any music commands at all, they are just extra commands

**Comment by galnir** [comment]
> Umm, I just got this error when running add-to-playlist command. The URL I used is https://youtube.com/playlist?list=PLQ7dL0qYMW8h2-F4p1ULlRw3kY5pLMAm_

I'll look into it

**Comment by Natemo6348** [comment]
If you try using my url, it didn't count the underscore as part of the url for some reason, so you might have to add the underscore to the end

**Comment by galnir** [comment]
@Natemo6348 I fixed your issue in b1abd5a
@Jriskamm I can't reproduce your problem on my end, did you clone this repo or copy the code to another bot?

**Comment by Bacon-Fixation** [comment]
@galnir still happens after commit
![image](https://user-images.githubusercontent.com/12632936/106397074-35fcb280-63d1-11eb-9b12-41c8ff23c5fa.png)

**Comment by galnir** [comment]
> @galnir i can replicate it
> ![image](https://user-images.githubusercontent.com/12632936/106397074-35fcb280-63d1-11eb-9b12-41c8ff23c5fa.png)

I'm not able to replicate it on both Windows and Debian.
For some reason the url you provide(same as the one I provide my bot on both instances) enters the if statement in line 197 although it shouldn't, since it entered the if statement in line 124

**Comment by Natemo6348** [comment]
@galnir I also get the issue with play command using the same url I used in add-to-playlist, but add-to-playlist is working now

**Comment by Natemo6348** [comment]
Nevermind forgot to pull play.js changes too, sorry

**Comment by Bacon-Fixation** [comment]
same

**Comment by Jriskamm** [comment]
> @Natemo6348 I fixed your issue in [b1abd5a](https://github.com/galnir/Master-Bot/commit/b1abd5a48983b87072e770de73c3779e68e7261c)
> @Jriskamm I can't reproduce your problem on my end, did you clone this repo or copy the code to another bot?

i cloned it too

**Comment by Jriskamm** [comment]
> another

it's only the link that doesn't work

**Comment by Jriskamm** [comment]
> > @galnir i can replicate it
> > ![image](https://user-images.githubusercontent.com/12632936/106397074-35fcb280-63d1-11eb-9b12-41c8ff23c5fa.png)
> 
> I'm not able to replicate it on both Windows and Debian.
> For some reason the url you provide(same as the one I provide my bot on both instances) enters the if statement in line 197 although it shouldn't, since it entered the if statement in line 124

ok just recloned it. it works now! thankuu
