### ISSUE TITLE
Playlist links are always shuffled

### ISSUE THREAD

**Issue by Bacon-Fixation** [galnir/Master-Bot#513]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
all YouTube playlist links are shuffled. It ignores the  `"AutomaticallyShuffleYouTubePlaylists": false` in the options.json file

**To Reproduce**
1. !play https://www.youtube.com/playlist?list=RDCLAK5uy_klY80tDUG8t6V0eXb5ttfGqRZZb8c5JZg
2. compare the playlist song order to the queue, its shuffled

**Expected behavior**
I expect that when I play a YouTube playlist it should be in the exact order as the link when  `AutomaticallyShuffleYouTubePlaylists` is false

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...] Windows/ Linux / Raspi-Pi OS
 - Node Version(Should be v12 atleast):  Nodejs 14.16.0
 - Is python 2.7 installed?: yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): All, I like testing (Windows, Linux, Heroku, Glitch, Ripl.it, Raspi-Pi OS)

**Additional context**
I'm not one for opening an issue, but I couldn't figure this out ... I can remove every instance of auto-shuffle from play.js and YouTube playlists are still shuffled... this has been frustrating me for the past couple of days, I don't know when it appeared nor why its shuffled even when shufflePlaylist function is commented out

**Comment by rafaeldamasceno** [comment]
It would be ideal if it was possible to have the playlist shuffle as a command flag. (like !p playlist -s)

**Comment by Bacon-Fixation** [comment]
issue has been solved with #541

Much Love
-Bacon

**Comment by rafaeldamasceno** [comment]
Sadly, I'm currently running a build with #541 and I don't think the issue is fixed. Perhaps #540 should be looked at since it also tries to fix this issue. Maybe #541 could be reverted and #540 merged in its place?

**Comment by rafaeldamasceno** [comment]
I just tested this again. The current master branch does still have the always shuffle bug, and #540 does fix it. The splice variable attribution is only a part of what causes the bug to happen, since it also involves issues with private videos in these playlist. The shuffle flag is also a great addition.

**Comment by galnir** [comment]
Merged #540 that adds -s flag
