### ISSUE TITLE
TypeError: Cannot read property 'client' of undefined

### ISSUE THREAD

**Issue by JamesGW-iOS** [galnir/Master-Bot#8]
When I try the play command, always after I say the name of the song it says in chat that something went wrong with the search of said song and then when I look in the console it says 
"TypeError: Cannot read property 'client' of undefined
    at new MessageEmbed 
\node_modules\discord.js\src\structures\MessageEmbed.js:10:60)
    at PlayCommand.run 
\commands\music\play.js:144:21)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async CommandMessage.run 
\node_modules\discord.js-commando\src\commands\message.js:212:19)
    at async CommandDispatcher.handleMessage 
\node_modules\discord.js-commando\src\dispatcher.js:127:19)
events.js:194"
Btw I took out where it says my name as a user like C:\Users\NAME\Docs\NAME.OF.FOLDER\ANOTHER.NAME

**Comment by galnir** [comment]
I've never seen this error so I researched a bit, this is not a code error.
There are many reasons this can happen, try these solutions:
1. Have you changed the owner id in index.js line 7 to your Discord user id?

2. Some guy got this exact error because he didn't have Git installed, as a result he installed the stable version of Commando which uses RichEmbed not MessageEmbed. So go ahead and run `npm install discordjs/Commando` in your terminal. If an error pops up, you don't have Git installed and that's the problem.

**Comment by CaptainYannick** [comment]
I've had the same issue tried both of your solutions but now I've got this error https://sourceb.in/7bf522532c are you able to help me?

**Comment by galnir** [comment]
@CaptainYannick Have you installed Commando and discord.js v12 correctly?
When running `npm view discord.js version` you should get 11.5.1
and you should get 0.10.0 from running `npm view discord.js-commando version`

**Comment by CaptainYannick** [comment]
@galnir Yes I have those versions

**Comment by CaptainYannick** [comment]
@galnir I fixed it forgot to install discord.js master

**Comment by galnir** [comment]
@JamesGW-iOS What about you?

**Comment by Beastskyler** [comment]
I am also having the same error as @CaptainYannick but no matter how many times I try to install discord.js master, I still get the same error.

**Comment by galnir** [comment]
@Beastskyler Did you install Commando correctly?

**Comment by Beastskyler** [comment]
> npm view discord.js-commando version

I got version 0.10.0. Also, if I uninstall both discord.js and commando, I can get my bot run but then if I run the play command, I get  TypeError: Cannot read property 'client' of undefined. So I reinstall both discord.js and commando.js and I get TypeError: Cannot read property 'extend' of undefined.

**Comment by galnir** [comment]
@Beastskyler Did you clone the repo or did you copy the music commands?

**Comment by Beastskyler** [comment]
Copy

**Comment by Beastskyler** [comment]
Your command is the only good one I could find that would go with my bot.

**Comment by galnir** [comment]
So you probably didn't create an instance of CommandoClient in your index.js if you didn't use Commando before. Take a look at my index.js file

**Comment by galnir** [comment]
Commando is a framework, so if you wish to use it you need to register command groups and stuff like that. Take a look at its [docs](https://discord.js.org/#/docs/commando/master/general/first-steps)

**Comment by Beastskyler** [comment]
This is what I have in my Index.js, I have my token in I it becasue every time I try to use a config.json, I can never get it to work.

const Commando = require('discord.js-commando');
const { CommandoClient } = require('discord.js-commando');
const discord = require('discord.js');
//const bot = new Commando.CommandoClient();
const TOKEN = 'TOKEN'
global.currentTeamMembers = [];
global.servers = {};
const prefix = 'gamer';
const bot = new Commando.CommandoClient({
    commandPrefix: 'gamer',
    owner: '623717679190245376',
    disableEveryone: true,
    unknownCommandResponse: false
});


bot.registry.registerGroup('simple', 'Simple');
bot.registry.registerGroup('join', 'Join');
bot.registry.registerGroup('music', 'Music');
bot.registry.registerGroup('fun', 'Fun');
bot.registry.registerDefaults();
bot.registry.registerCommandsIn(__dirname + '/commands');

bot.on('message', function(message){
    if(message.content == 'Hello')
    {
        message.channel.sendMessage('Hello ' + message.author + ' how are you?');
    }
    if(message.content == 'siege'){
        message.channel.sendMessage('@everyone Hint! Hint!');
        }
  //  if(message.content == "Monsters"){
  //      for(let i = 0; i < 20; i++){
  //          message.channel.send({ files: ["./Cursed.jpg"] });
 //           }           
 //       }
 //       if(message.content == "Gnome bomb"){
 //           for(let i = 0; i < 20; i++){
 //               message.channel.sendMessage("You've been gnomed!!");
 //       }
 //   }
//    if(message.content == 'Stalk bomb'){
//        for(let i = 0; i < 20; i++) {
//            message.channel.sendMessage("You will now be stalked!!");
//        }
 //   }
  //  if(message.content == "Apex"){
  //      for(let i = 0; i < 20; i++){
   //         message.channel.send({ files: ["./Apex.jpg"] });
    //    }
   // }

});




bot.on('ready',function(){
    console.log("Ready");
    bot.user.setPresence({ game: { name: 'with depression' }, status: 'online' });
bot.user.setActivity('with depression', 'https://www.youtube.com/channel/UCuayZt060i2TldTNk0wpWzQ?view_as=subscriber');
})

bot.login(TOKEN);

**Comment by Beastskyler** [comment]
I have used commando for all of my commands

**Comment by galnir** [comment]
Add me on discord - hyperzone#1185 
I'll try to solve your problem on dms and when we solve it I'll comment the solution here

**Comment by galnir** [comment]
Beastskyler's issue was a var naming issue

**Comment by galnir** [comment]
Will reopen if you still have this

**Comment by painownage1** [comment]
still got this

**Comment by galnir** [comment]
@painownage1 got what? Did you install the dependencies correctly?

**Comment by LuuNyX** [comment]
Personnaly, I have this error:

**Comment by galnir** [comment]
@LuuNyX Then you didn't install discordjs or Commando correctly, did you clone this repo or copy code?

**Comment by LuuNyX** [comment]
> @LuuNyX Then you didn't install discordjs or Commando correctly, did you clone this repo or copy code?

No I fully use my own bot, I not copied this

**Comment by galnir** [comment]
@LuuNyX You probably have discordjs v11 installed and not v12. What do you mean use my own bot? Did you even clone this repo? If you did, all you need to do is follow the instructions and it will work

**Comment by Lurgrid** [comment]
Hello, I didn't quite understand the messages before. I have the same error. 
Personally, my bot throws like this : 
const Discord = require("discord.js");
var bot = new Discord.Client();
bot.login(token);

**Comment by NiNj4HAXYT** [comment]
TypeError: Cannot read property 'client' of undefined
    at new MessageEmbed (C:\Windows.old\Users\tukin\Desktop\BOT\Kaz#0001\node_modules\discord.js\src\structures\MessageEmbed.js:13:60)
    at Object.<anonymous> (C:\Windows.old\Users\tukin\Desktop\BOT\Kaz#0001\index.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by NemSeih** [comment]
I resolved this error updating my NPM.

**Try it in your terminal:**
`npm install -g npm`


_it may take between 5 and 15 minutes_

**Comment by anish-kum** [comment]
I am having trouble as my bot is saying Uncaught TypeError: Cannot read property 'client' of undefined whenever I give it  a command for embeds. What do I do?

**Comment by NemSeih** [comment]
@anish-kum, can you send the code?

**Comment by anish-kum** [comment]
sure

**Comment by anish-kum** [comment]
I will remove the token part though

**Comment by anish-kum** [comment]
const Discord = require('discord.js');
const bot = new Discord.Client();
const PREFIX = '!';
const RED_ROLE = '795365856288702475';
const BLUE_ROLE = '795365944724553768';
var version = '1.01';




bot.on('ready', () => {
  console.log('The bot is ready.');
  bot.user.setActivity("Type !command. HATCHING RIOLU LIKE A BOSS")


  
});

if (bot.on) {
  
  bot.on('message', msg=>{
    if (msg.content === "!Joke") {
      msg.channel.send("Q: Whats the best book?   A: The chromebook!")
            
    }
  
  });
  bot.on('message', msg=>{
    if (msg.content === "!Welcome Message") {
      msg.reply("Welcome to #general chat! Chat with anyone, but make sure to follow the guidlines MEE6 listed! For further use of bot, please type in !command for commands for the robot, and for further questions don't hesitate at all to DM @SPZ_Zapper!!")
      msg.reply(`:grinning: `)
   
    }
    
    });
  bot.on('message', message=> {
     if (message.content === '!smileyface') {
      message.channel.send(`:grinning: `)

      }

    });
  
}
bot.on('message', message=> {

  let args = message.content.substring(PREFIX.length).split(" ");

  switch(args[0]) {
    case 'userinfo':
      const embed  = new Discord.MessageEmbed()
      .setTitle('User Information')
      .addField('User name', message.author.username)
      .addField('User ID. Note... will not harm your account if others see it.', message.author.id)
      .addField('Version', version)
      .addField('Current Server', message.guild.name)
      .addField('Date joined', message.guild.joinedAt)
      .addField('Account created', message.author.createdAt)
      .setThumbnail(message.author.displayAvatarURL())
      .setColor(0xF1C40F)
      .setThumbnail(message.author.avatar)
      
      
      message.channel.send(embed);
    break;
  }
  
});
bot.on('message', message=> {

  let args = message.content.substring(PREFIX.length).split(" ");

  switch(args[0]) {
    case 'command':
      const embed = new Discord.MessageEmbed()
      .setColor('#0099ff')
      .setTitle('Commands for Lucario Bot!!!')
      .addFields(
        {name: 'This is a way to access Lucarios commands!', value: 'Note that these commands will either be updated, or new commands will be added. These commands are case sensitive!!'},
        {name: '!userinfo', value: 'Type !userinfo in for a quick summary of yourself. Note that you can only see yourself, but not others.'},
        {name: '!Joke', value: 'Type !Joke in for the bot to give you a joke! There is only one so far, but will keep on updating!!'},
        {name: '!Welcome Message', value: 'Type in !Welcome Message for a nice warm welcome from the Lucario bot!!'},
        {name: '!jointeam', value: 'Type this in to see the exclsuive roles you can get for this server. Join one team,'},
        {name: '!lucariobio', value: 'Type this in to see the story of the developement of the bot!!'},
        {name: '!poll', value: 'Type this in, there will then be a new embed for further instructions.'},
        )
      message.channel.send(embed);
      
    
  }

});
bot.on('message', message => {
  let args = message.content.substring(PREFIX.length).split(" ");

  switch(args[0]) {
    case 'lucariobio':
      const embed = new Discord.MessageEmbed()
      .setTitle('Bio on Lucario bot, and how it was developed.')
      .addFields(
        {name: 'Bio of LUCARIO BOT!!', value: 'The Lucario bot was fully developed by Anish K. Fully developed in Javascript with an abundance of commands. You can always help with the developent of the bot.'},
      )
    message.channel.send(embed);

  }



});
bot.on('message', message=> {

  let args = message.content.substring(PREFIX.length).split(" ");

  switch(args[0]) {
    case 'jointeam':
      const embed = new Discord.MessageEmbed()
      .setColor('#0099ff')
      .setTitle('Teams to join. Pick wisely, once you pick, this is the permenant team you will be on. Contact @SPZ_Zapper is you want to change. Once you get the role you will unlock a chat. Remember to only pick one role, and you will unlock one chat.')
      .addFields(
        {name: '+RED_ROLE', value: 'Type this in to get the exclusive Red Role  Groudon role. To see roles click on your self when you chat.'},
        {name: '+BLUE_ROLE', value: 'Type this in to get the exclusive Blue Role Kyogre role. To see the roles click on your self when you chat. '},
      )
      message.channel.send(embed);
    
  }
});
bot.on('message', message=> {
  let args = message.content.substring(PREFIX.length).split(" ");

  switch(args[0]) {
    case 'poll':
      const Embed = new Discord.MessageEmbed()
      .setColor(0xffc300)
      .setTitle('Initiate Poll')
      .setDescription('This is how you can initiate any poll. You first type in !poll then space, then the question you want. Here is an example !poll Are cats better than Dogs?')

      if(!args[1]) {
        message.channel.send(Embed)
        break;
      }

      let msgArgs = args.slice(1).join(" ");

      message.channel.send( "📖" + "**" + msgArgs + "**").then(messageReaction => {
        messageReaction.react('✅');
        messageReaction.react('❌');
        

      });
      
    break;
  }

});
bot.on('message', (message) => {
   
   

  if (message.content === '+RED_ROLE') {
    message.member.roles.add(RED_ROLE)
    message.reply('Red role successfully added!')
    message.react('👍')
     if (message.reactions = `:thumbsup`) {
       message.reply('ha')
     }
    
  }
  
 
  
  if (message.content === '+BLUE_ROLE') {
    message.member.roles.add(BLUE_ROLE)
    message.reply('Blue role successfully added!')
    message.react('👍')
    
   }
      

  

    
  
    
});
bot.login(token);

**Comment by NemSeih** [comment]
Weird.
Try to replace `Discord.MessageEmbed()` to `Discord.RichEmbed`.

**Comment by anish-kum** [comment]
Ok

**Comment by anish-kum** [comment]
And te wierdest part is that it suddenly happened
Everything was working fine before.
I did install cheerio and other stuff in the terminal if that did anything.

**Comment by NemSeih** [comment]
> I resolved this error updating my NPM and my Discord.JS.
> 
> **Try it in your terminal:**
> `npm install -g npm`
> `npm install discord.js`
> 
> _it may take between 5 and 15 minutes_

You can try it too /\

**Comment by anish-kum** [comment]
I tried that. The poll part is working but all the other embeds are not.

**Comment by NemSeih** [comment]
You can replace all your embeds to RichEmbed with no probs...

**Comment by anish-kum** [comment]
I did

**Comment by anish-kum** [comment]
Still says cannot read property of client of undefined

**Comment by NemSeih** [comment]
Are you using DiscordJs v12+?

**Comment by anish-kum** [comment]
How do you check?

**Comment by anish-kum** [comment]
I downloaded this  all last week

**Comment by anish-kum** [comment]
And this all worked when I used Discord.Message.Embed yesterday

**Comment by anish-kum** [comment]
Also, I downloaded something called cheerio and request packages if that has anything to do with it.

**Comment by NemSeih** [comment]
That is really weird.
To check the vers, do it in your terminal:
`npm view discord.js version`

**Comment by NemSeih** [comment]
> Also, I downloaded something called cheerio and request packages if that has anything to do with it.

what did it do? (cheerio)

**Comment by anish-kum** [comment]
OH MY GOD. I HAVE VERSION 15

**Comment by NemSeih** [comment]
really?
that is REALLY weird

**Comment by anish-kum** [comment]
When I do node -v. It says v15.5.0

**Comment by NemSeih** [comment]
oh, its node's version

Do it:
`npm view discord.js version`

**Comment by anish-kum** [comment]
Now it says ncaught TypeError: (intermediate value).setColor(...).setTitle(...).addFields is not a function when I do !command which is an embed

**Comment by anish-kum** [comment]
Version 12.5.1 I checked now. Look at the message above though.

**Comment by NemSeih** [comment]
i really do no what is it

i'm testing in my pc, I already answer here

**Comment by anish-kum** [comment]
So what now?

**Comment by NemSeih** [comment]
wait pls

**Comment by NemSeih** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/54189840/103939745-011b7980-510b-11eb-9c9e-e8ebbb2daa29.png)
🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔

**Comment by anish-kum** [comment]
How though?

**Comment by NemSeih** [comment]
I used `const embed = new Discord.MessageEmbed()`, and it works fine

**Comment by anish-kum** [comment]
Not for me sadly

**Comment by NemSeih** [comment]
![image](https://user-images.githubusercontent.com/54189840/103940028-7f781b80-510b-11eb-94ff-3a61548734cc.png)

yeah it works fine

**Comment by anish-kum** [comment]
Not for me though. Its sad because I put a lot of effort and it does not work.

**Comment by NemSeih** [comment]
![image](https://user-images.githubusercontent.com/54189840/103940104-9d458080-510b-11eb-8d53-a45198c8e04f.png)

I used v12.5.1 with this code:


> const Discord = require('discord.js');
> const bot = new Discord.Client();
> const PREFIX = '!';
> const RED_ROLE = '795365856288702475';
> const BLUE_ROLE = '795365944724553768';
> var version = '1.01';
> 
> bot.on('ready', () => {
> console.log('The bot is ready.');
> bot.user.setActivity("Type !command. HATCHING RIOLU LIKE A BOSS")
> 
> });
> 
> if (bot.on) {
> 
> bot.on('message', msg=>{
> if (msg.content === "!Joke") {
> msg.channel.send("Q: Whats the best book? A: The chromebook!")
> 
> ```
> }
> ```
> 
> });
> bot.on('message', msg=>{
> if (msg.content === "!Welcome Message") {
> msg.reply("Welcome to #general chat! Chat with anyone, but make sure to follow the guidlines MEE6 listed! For further use of bot, please type in !command for commands for the robot, and for further questions don't hesitate at all to DM @SPZ_Zapper!!")
> msg.reply(`:grinning: `)
> 
> ```
> }
> 
> });
> ```
> 
> bot.on('message', message=> {
> if (message.content === '!smileyface') {
> message.channel.send(`:grinning: `)
> 
> ```
>   }
> 
> });
> ```
> 
> }
> bot.on('message', message=> {
> 
> let args = message.content.substring(PREFIX.length).split(" ");
> 
> switch(args[0]) {
> case 'userinfo':
> const embed = new Discord.MessageEmbed()
> .setTitle('User Information')
> .addField('User name', message.author.username)
> .addField('User ID. Note... will not harm your account if others see it.', message.author.id)
> .addField('Version', version)
> .addField('Current Server', message.guild.name)
> .addField('Date joined', message.guild.joinedAt)
> .addField('Account created', message.author.createdAt)
> .setThumbnail(message.author.displayAvatarURL())
> .setColor(0xF1C40F)
> .setThumbnail(message.author.avatar)
> 
> ```
>   message.channel.send(embed);
> break;
> ```
> 
> }
> 
> });
> bot.on('message', message=> {
> 
> let args = message.content.substring(PREFIX.length).split(" ");
> 
> switch(args[0]) {
> case 'command':
> const embed = new Discord.MessageEmbed()
> .setColor('#0099ff')
> .setTitle('Commands for Lucario Bot!!!')
> .addFields(
> {name: 'This is a way to access Lucarios commands!', value: 'Note that these commands will either be updated, or new commands will be added. These commands are case sensitive!!'},
> {name: '!userinfo', value: 'Type !userinfo in for a quick summary of yourself. Note that you can only see yourself, but not others.'},
> {name: '!Joke', value: 'Type !Joke in for the bot to give you a joke! There is only one so far, but will keep on updating!!'},
> {name: '!Welcome Message', value: 'Type in !Welcome Message for a nice warm welcome from the Lucario bot!!'},
> {name: '!jointeam', value: 'Type this in to see the exclsuive roles you can get for this server. Join one team,'},
> {name: '!lucariobio', value: 'Type this in to see the story of the developement of the bot!!'},
> {name: '!poll', value: 'Type this in, there will then be a new embed for further instructions.'},
> )
> message.channel.send(embed);
> 
> }
> 
> });
> bot.on('message', message => {
> let args = message.content.substring(PREFIX.length).split(" ");
> 
> switch(args[0]) {
> case 'lucariobio':
> const embed = new Discord.MessageEmbed()
> .setTitle('Bio on Lucario bot, and how it was developed.')
> .addFields(
> {name: 'Bio of LUCARIO BOT!!', value: 'The Lucario bot was fully developed by (Dont want to show name) Fully developed in Javascript with an abundance of commands. You can always help with the developent of the bot.'},
> )
> message.channel.send(embed);
> 
> }
> 
> });
> bot.on('message', message=> {
> 
> let args = message.content.substring(PREFIX.length).split(" ");
> 
> switch(args[0]) {
> case 'jointeam':
> const embed = new Discord.MessageEmbed()
> .setColor('#0099ff')
> .setTitle('Teams to join. Pick wisely, once you pick, this is the permenant team you will be on. Contact @SPZ_Zapper is you want to change. Once you get the role you will unlock a chat. Remember to only pick one role, and you will unlock one chat.')
> .addFields(
> {name: '+RED_ROLE', value: 'Type this in to get the exclusive Red Role Groudon role. To see roles click on your self when you chat.'},
> {name: '+BLUE_ROLE', value: 'Type this in to get the exclusive Blue Role Kyogre role. To see the roles click on your self when you chat. '},
> )
> message.channel.send(embed);
> 
> }
> });
> bot.on('message', message=> {
> let args = message.content.substring(PREFIX.length).split(" ");
> 
> switch(args[0]) {
> case 'poll':
> const Embed = new Discord.MessageEmbed()
> .setColor(0xffc300)
> .setTitle('Initiate Poll')
> .setDescription('This is how you can initiate any poll. You first type in !poll then space, then the question you want. Here is an example !poll Are cats better than Dogs?')
> 
> ```
>   if(!args[1]) {
>     message.channel.send(Embed)
>     break;
>   }
> 
>   let msgArgs = args.slice(1).join(" ");
> 
>   message.channel.send( "📖" + "**" + msgArgs + "**").then(messageReaction => {
>     messageReaction.react('✅');
>     messageReaction.react('❌');
>     
> 
>   });
>   
> break;
> ```
> 
> }
> 
> });
> bot.on('message', (message) => {
> 
> if (message.content === '+RED_ROLE') {
> message.member.roles.add(RED_ROLE)
> message.reply('Red role successfully added!')
> message.react('👍')
> if (message.reactions = `:thumbsup`) {
> message.reply('ha')
> }
> 
> }
> 
> if (message.content === '+BLUE_ROLE') {
> message.member.roles.add(BLUE_ROLE)
> message.reply('Blue role successfully added!')
> message.react('👍')
> 
> }
> 
> });
> bot.login(token);

**Comment by anish-kum** [comment]
It worked yesterday very well.

**Comment by NemSeih** [comment]
did you use a VPS or any server?

**Comment by anish-kum** [comment]
what do you mean?

**Comment by NemSeih** [comment]
The BOT is running in your PC (cmd, Visual Studio Code Terminal) or its in a server (Virtual Private Server [VPS])

**Comment by anish-kum** [comment]
Visual Studio Code terminal

**Comment by NemSeih** [comment]
I really dont know what is this bug... I'm sorry :/
I used the code with `Discord.MessageEmbed()`, in discord.js v12.5.1 and it works fine.

**Comment by anish-kum** [comment]
Ok. I guess

**Comment by anish-kum** [comment]
Really sad about this.

**Comment by anish-kum** [comment]
@NemSeih? Now its just saying Uncaught TypeError: (intermediate value).setColor(...).setTitle(...).addFields is not a function for !command, !jointeam, etc?

**Comment by galnir** [comment]
@anish-kum The code you're posting here isn't from this repository, you can't get help unless you use the code here without modifying it too much

**Comment by anish-kum** [comment]
Ok. sorry
